// The twin transform: (source + intent) -> H5P content plan + content.json per item.
// Uses an LLM when AI_GATEWAY_API_KEY or ANTHROPIC_API_KEY is set; otherwise a
// deterministic mock so the whole pipe runs offline.

import { generateText } from "ai";
import type { ImportIntent, TwinResult, TwinSource, GeneratedItem } from "./types";
import { contentType } from "./h5p/contentTypes";
import {
  buildSummary,
  buildSingleChoiceSet,
  buildTrueFalse,
  buildFlashcards,
} from "./h5p/mockContent";
import { loadCalibrationSamples } from "./calibration";

function hasModel() {
  return Boolean(process.env.AI_GATEWAY_API_KEY || process.env.ANTHROPIC_API_KEY);
}

async function resolveSourceText(source: TwinSource): Promise<string> {
  if (source.kind === "text") return source.value;
  // url
  try {
    const res = await fetch(source.value, { headers: { "user-agent": "h5p-twin/0.1" } });
    const html = await res.text();
    return html
      .replace(/<script[\s\S]*?<\/script>/gi, " ")
      .replace(/<style[\s\S]*?<\/style>/gi, " ")
      .replace(/<[^>]+>/g, " ")
      .replace(/\s+/g, " ")
      .trim()
      .slice(0, 12000);
  } catch {
    return `(could not fetch ${source.value})`;
  }
}

// --- crude concept/QA extraction for the mock engine ---------------------------

function extractConcepts(text: string, n = 5): string[] {
  const stop = new Set(
    "the a an and or of to in on for with is are was were be been being this that these those it its as at by from into than then so such not no yes you your we our they their he she his her".split(
      " ",
    ),
  );
  const freq = new Map<string, number>();
  for (const raw of text.toLowerCase().match(/[a-z][a-z-]{3,}/g) ?? []) {
    if (stop.has(raw)) continue;
    freq.set(raw, (freq.get(raw) ?? 0) + 1);
  }
  return [...freq.entries()]
    .sort((a, b) => b[1] - a[1])
    .slice(0, n)
    .map(([w]) => w[0].toUpperCase() + w.slice(1));
}

function mockEngine(text: string, intent: ImportIntent): TwinResult {
  const concepts = extractConcepts(text, 6);
  const sentences = (text.match(/[^.!?]{20,}[.!?]/g) ?? []).map((s) => s.trim());
  const qa = concepts.map((c, i) => ({
    question: `Which statement about ${c} is correct?`,
    correct: sentences[i]?.slice(0, 140) ?? `${c} is a key idea in this material.`,
    distractors: [
      `${c} does not appear in this material.`,
      `${c} contradicts the source.`,
    ],
  }));

  const items: GeneratedItem[] = [];
  intent.contentTypes.forEach((typeName, idx) => {
    const def = contentType(typeName);
    if (!def) return;
    const base = {
      id: `item-${idx}`,
      contentType: typeName,
      title: `${def.label}: ${intent.learningGoal || concepts[0] || "Overview"}`,
      concepts: concepts.slice(0, 4),
      rationale: `Generated by the mock engine from the ${concepts.length} most frequent concepts; ${intent.emphasis} emphasis.`,
      mainLibrary: def.library,
    };
    let contentJson: unknown;
    switch (typeName) {
      case "H5P.Summary":
        contentJson = buildSummary(concepts);
        break;
      case "H5P.SingleChoiceSet":
        contentJson = buildSingleChoiceSet(qa);
        break;
      case "H5P.TrueFalse":
        contentJson = buildTrueFalse(
          qa[0]?.correct ?? `${concepts[0]} is discussed in this material.`,
          true,
        );
        break;
      case "H5P.Flashcards":
        contentJson = buildFlashcards(
          concepts.map((c, i) => ({
            term: c,
            definition: sentences[i]?.slice(0, 160) ?? `Definition of ${c}.`,
          })),
        );
        break;
      default:
        return;
    }
    items.push({ ...base, contentJson });
  });

  return {
    sourceSummary: sentences.slice(0, 2).join(" ") || text.slice(0, 240),
    planNarrative: `Mock plan: ${items.length} artifact(s) built from concepts ${concepts
      .slice(0, 4)
      .join(", ")}. Set an API key to use the model engine for calibrated output.`,
    items,
    engine: "mock",
  };
}

// --- model engine -------------------------------------------------------------

async function modelEngine(text: string, intent: ImportIntent): Promise<TwinResult> {
  const samples = await loadCalibrationSamples();
  const model = process.env.AI_GATEWAY_API_KEY
    ? "anthropic/claude-sonnet-4.5"
    : "anthropic/claude-sonnet-4-5";

  const sampleBlock = samples.length
    ? `Here are REAL Smart Import outputs to match in structure and style:\n\n${samples
        .map(
          (s) =>
            `--- ${s.mainLibrary} (from source: ${s.sourceHint}) ---\n${JSON.stringify(
              s.contentJson,
            ).slice(0, 4000)}`,
        )
        .join("\n\n")}`
    : "No real Smart Import samples are available for calibration; follow the public H5P content specs.";

  const prompt = `You are a faithful digital twin of H5P.com's Smart Import. Given source material and an educator's intent, produce an H5P content plan and the content.json for each requested content type.

SOURCE:
${text.slice(0, 12000)}

INTENT:
${JSON.stringify(intent, null, 2)}

${sampleBlock}

Return ONLY JSON of this shape:
{
  "sourceSummary": string,
  "planNarrative": string,
  "items": [
    {
      "id": string,
      "contentType": "H5P.Summary" | "H5P.SingleChoiceSet" | "H5P.TrueFalse" | "H5P.Flashcards",
      "title": string,
      "concepts": string[],
      "rationale": string,
      "mainLibrary": string,
      "contentJson": object
    }
  ]
}
Only include contentType values listed in INTENT.contentTypes. Make contentJson valid for the real H5P library.`;

  const { text: out } = await generateText({ model, prompt, temperature: 0.4 });
  const json = out.slice(out.indexOf("{"), out.lastIndexOf("}") + 1);
  const parsed = JSON.parse(json) as Omit<TwinResult, "engine">;
  return { ...parsed, engine: "model" };
}

export async function runTwin(
  source: TwinSource,
  intent: ImportIntent,
): Promise<TwinResult> {
  const text = await resolveSourceText(source);
  if (hasModel()) {
    try {
      return await modelEngine(text, intent);
    } catch (err) {
      console.error("model engine failed, falling back to mock:", err);
    }
  }
  return mockEngine(text, intent);
}
